// Package costexplorer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package costexplorer

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for FilterServices.
const (
	Compute FilterServices = "compute"
	Image   FilterServices = "image"
	Volume  FilterServices = "volume"
)

// Valid indicates whether the value is a known member of the FilterServices enum.
func (e FilterServices) Valid() bool {
	switch e {
	case Compute:
		return true
	case Image:
		return true
	case Volume:
		return true
	default:
		return false
	}
}

// Defines values for ForecastRequestGranularity.
const (
	ForecastRequestGranularityDaily   ForecastRequestGranularity = "daily"
	ForecastRequestGranularityMonthly ForecastRequestGranularity = "monthly"
)

// Valid indicates whether the value is a known member of the ForecastRequestGranularity enum.
func (e ForecastRequestGranularity) Valid() bool {
	switch e {
	case ForecastRequestGranularityDaily:
		return true
	case ForecastRequestGranularityMonthly:
		return true
	default:
		return false
	}
}

// Defines values for ForecastRequestMetric.
const (
	ForecastRequestMetricCost ForecastRequestMetric = "cost"
)

// Valid indicates whether the value is a known member of the ForecastRequestMetric enum.
func (e ForecastRequestMetric) Valid() bool {
	switch e {
	case ForecastRequestMetricCost:
		return true
	default:
		return false
	}
}

// Defines values for RequestGranularity.
const (
	RequestGranularityDaily   RequestGranularity = "daily"
	RequestGranularityHourly  RequestGranularity = "hourly"
	RequestGranularityMonthly RequestGranularity = "monthly"
)

// Valid indicates whether the value is a known member of the RequestGranularity enum.
func (e RequestGranularity) Valid() bool {
	switch e {
	case RequestGranularityDaily:
		return true
	case RequestGranularityHourly:
		return true
	case RequestGranularityMonthly:
		return true
	default:
		return false
	}
}

// Defines values for RequestGroupBy.
const (
	ProjectId  RequestGroupBy = "project_id"
	Region     RequestGroupBy = "region"
	ResourceId RequestGroupBy = "resource_id"
	Service    RequestGroupBy = "service"
	UsageType  RequestGroupBy = "usage_type"
)

// Valid indicates whether the value is a known member of the RequestGroupBy enum.
func (e RequestGroupBy) Valid() bool {
	switch e {
	case ProjectId:
		return true
	case Region:
		return true
	case ResourceId:
		return true
	case Service:
		return true
	case UsageType:
		return true
	default:
		return false
	}
}

// Defines values for RequestMetrics.
const (
	RequestMetricsCost          RequestMetrics = "cost"
	RequestMetricsUsageQuantity RequestMetrics = "usage_quantity"
)

// Valid indicates whether the value is a known member of the RequestMetrics enum.
func (e RequestMetrics) Valid() bool {
	switch e {
	case RequestMetricsCost:
		return true
	case RequestMetricsUsageQuantity:
		return true
	default:
		return false
	}
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	//
	// Example: Property foo is required but is missing.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	//
	// Example: https://example.com/error-log/abc123
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	//
	// Example: 400
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	//
	// Example: Bad Request
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	//
	// Example: https://example.com/errors/example
	Type *string `json:"type,omitempty"`
}

// Filter defines model for Filter.
type Filter struct {
	ProjectIds *[]string         `json:"project_ids,omitempty"`
	Regions    *[]string         `json:"regions,omitempty"`
	Services   *[]FilterServices `json:"services,omitempty"`
	UsageTypes *[]string         `json:"usage_types,omitempty"`
}

// FilterServices defines model for Filter.Services.
type FilterServices string

// ForecastRequest defines model for ForecastRequest.
type ForecastRequest struct {
	// AllowPartial Aggregator only: forecast from the regions that answered, listing the rest in missing_regions.
	AllowPartial *bool                      `json:"allow_partial,omitempty"`
	Filter       *Filter                    `json:"filter,omitempty"`
	Granularity  ForecastRequestGranularity `json:"granularity"`
	LookbackDays *int64                     `json:"lookback_days,omitempty"`
	Metric       *ForecastRequestMetric     `json:"metric,omitempty"`
	TimePeriod   TimePeriod                 `json:"time_period"`
}

// ForecastRequestGranularity defines model for ForecastRequest.Granularity.
type ForecastRequestGranularity string

// ForecastRequestMetric defines model for ForecastRequest.Metric.
type ForecastRequestMetric string

// ForecastResponse defines model for ForecastResponse.
type ForecastResponse struct {
	AsOf                  time.Time         `json:"as_of"`
	Estimated             bool              `json:"estimated"`
	ForecastResultsByTime *[]ForecastResult `json:"forecast_results_by_time"`
	HistoryPeriod         TimePeriod        `json:"history_period"`

	// MissingRegions Regions left out of an allow_partial forecast because they did not answer.
	MissingRegions *[]string `json:"missing_regions,omitempty"`
	Model          string    `json:"model"`

	// Regions The regions the history covers and how far each one's data is complete.
	Regions *[]RegionStatus `json:"regions,omitempty"`
	Total   Metric          `json:"total"`
}

// ForecastResult defines model for ForecastResult.
type ForecastResult struct {
	MeanValue  string     `json:"mean_value"`
	TimePeriod TimePeriod `json:"time_period"`
}

// Group defines model for Group.
type Group struct {
	Keys    *[]string         `json:"keys"`
	Metrics map[string]Metric `json:"metrics"`
}

// Metric defines model for Metric.
type Metric struct {
	Amount string `json:"amount"`
	Unit   string `json:"unit"`
}

// RegionStatus defines model for RegionStatus.
type RegionStatus struct {
	DataThrough time.Time `json:"data_through"`
	Name        string    `json:"name"`
}

// Request defines model for Request.
type Request struct {
	// AllowPartial Aggregator only: return the regions that answered, listing the rest in missing_regions, instead of failing the report.
	AllowPartial *bool `json:"allow_partial,omitempty"`

	// AsOf Optional reporting cutoff; defaults to the current time and cannot be in the future.
	AsOf        *time.Time         `json:"as_of,omitempty"`
	Filter      *Filter            `json:"filter,omitempty"`
	Granularity RequestGranularity `json:"granularity"`
	GroupBy     *[]RequestGroupBy  `json:"group_by,omitempty"`
	Metrics     *[]RequestMetrics  `json:"metrics,omitempty"`
	TimePeriod  TimePeriod         `json:"time_period"`
}

// RequestGranularity defines model for Request.Granularity.
type RequestGranularity string

// RequestGroupBy defines model for Request.GroupBy.
type RequestGroupBy string

// RequestMetrics defines model for Request.Metrics.
type RequestMetrics string

// Response defines model for Response.
type Response struct {
	AsOf             time.Time `json:"as_of"`
	Currency         string    `json:"currency"`
	GroupDefinitions *[]string `json:"group_definitions"`

	// MissingRegions Regions left out of an allow_partial report because they did not answer.
	MissingRegions *[]string `json:"missing_regions,omitempty"`
	PricingVersion string    `json:"pricing_version"`

	// Regions The regions this report covers and how far each one's data is complete.
	Regions       *[]RegionStatus `json:"regions,omitempty"`
	ResultsByTime *[]ResultByTime `json:"results_by_time"`
}

// ResultByTime defines model for ResultByTime.
type ResultByTime struct {
	Estimated   bool               `json:"estimated"`
	Groups      *[]Group           `json:"groups"`
	TimePeriod  TimePeriod         `json:"time_period"`
	Total       map[string]Metric  `json:"total"`
	UsageByUnit *map[string]Metric `json:"usage_by_unit,omitempty"`
}

// TimePeriod defines model for TimePeriod.
type TimePeriod struct {
	// End Exclusive interval end (RFC3339).
	End time.Time `json:"end"`

	// Start Inclusive UTC interval start (RFC3339).
	Start time.Time `json:"start"`
}

// CreateCostForecastJSONRequestBody defines body for CreateCostForecast for application/json ContentType.
type CreateCostForecastJSONRequestBody = ForecastRequest

// CreateCostReportJSONRequestBody defines body for CreateCostReport for application/json ContentType.
type CreateCostReportJSONRequestBody = Request

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CreateCostForecastWithBody Calculate a cost forecast
	//
	// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
	CreateCostForecastWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCostForecast Calculate a cost forecast
	//
	// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
	CreateCostForecast(ctx context.Context, body CreateCostForecastJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCostReportWithBody Calculate a cost and usage report
	//
	// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
	CreateCostReportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCostReport Calculate a cost and usage report
	//
	// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
	CreateCostReport(ctx context.Context, body CreateCostReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CreateCostForecastWithBody Calculate a cost forecast
//
// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
func (c *Client) CreateCostForecastWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCostForecastRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCostForecast Calculate a cost forecast
//
// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
func (c *Client) CreateCostForecast(ctx context.Context, body CreateCostForecastJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCostForecastRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCostReportWithBody Calculate a cost and usage report
//
// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
func (c *Client) CreateCostReportWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCostReportRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCostReport Calculate a cost and usage report
//
// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
func (c *Client) CreateCostReport(ctx context.Context, body CreateCostReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCostReportRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateCostForecastRequest calls the generic CreateCostForecast builder with application/json body
func NewCreateCostForecastRequest(server string, body CreateCostForecastJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCostForecastRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCostForecastRequestWithBody constructs an http.Request for the CreateCostForecast method, with any body, and a specified content type
func NewCreateCostForecastRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cost_forecasts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateCostReportRequest calls the generic CreateCostReport builder with application/json body
func NewCreateCostReportRequest(server string, body CreateCostReportJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCostReportRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCostReportRequestWithBody constructs an http.Request for the CreateCostReport method, with any body, and a specified content type
func NewCreateCostReportRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cost_reports")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CreateCostForecastWithBodyWithResponse Calculate a cost forecast
	//
	// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
	CreateCostForecastWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCostForecastResponse, error)

	// CreateCostForecastWithResponse Calculate a cost forecast
	//
	// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
	CreateCostForecastWithResponse(ctx context.Context, body CreateCostForecastJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCostForecastResponse, error)

	// CreateCostReportWithBodyWithResponse Calculate a cost and usage report
	//
	// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
	CreateCostReportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCostReportResponse, error)

	// CreateCostReportWithResponse Calculate a cost and usage report
	//
	// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
	CreateCostReportWithResponse(ctx context.Context, body CreateCostReportJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCostReportResponse, error)
}

type CreateCostForecastResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ForecastResponse
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *ErrorModel
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *ErrorModel
	// ApplicationproblemJSON413 the response for an HTTP 413 `application/problem+json` response
	ApplicationproblemJSON413 *ErrorModel
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *ErrorModel
	// ApplicationproblemJSON429 the response for an HTTP 429 `application/problem+json` response
	ApplicationproblemJSON429 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *ErrorModel
	// ApplicationproblemJSON504 the response for an HTTP 504 `application/problem+json` response
	ApplicationproblemJSON504 *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateCostForecastResponse) GetJSON200() *ForecastResponse {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON401() *ErrorModel {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON403() *ErrorModel {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON413 returns the response for an HTTP 413 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON413() *ErrorModel {
	return r.ApplicationproblemJSON413
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON422() *ErrorModel {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON429 returns the response for an HTTP 429 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON429() *ErrorModel {
	return r.ApplicationproblemJSON429
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON503() *ErrorModel {
	return r.ApplicationproblemJSON503
}

// GetApplicationproblemJSON504 returns the response for an HTTP 504 `application/problem+json` response
func (r CreateCostForecastResponse) GetApplicationproblemJSON504() *ErrorModel {
	return r.ApplicationproblemJSON504
}

// GetBody returns the raw response body bytes
func (r CreateCostForecastResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateCostForecastResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCostForecastResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateCostForecastResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateCostReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *ErrorModel
	// ApplicationproblemJSON403 the response for an HTTP 403 `application/problem+json` response
	ApplicationproblemJSON403 *ErrorModel
	// ApplicationproblemJSON413 the response for an HTTP 413 `application/problem+json` response
	ApplicationproblemJSON413 *ErrorModel
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *ErrorModel
	// ApplicationproblemJSON429 the response for an HTTP 429 `application/problem+json` response
	ApplicationproblemJSON429 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *ErrorModel
	// ApplicationproblemJSON504 the response for an HTTP 504 `application/problem+json` response
	ApplicationproblemJSON504 *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateCostReportResponse) GetJSON200() *Response {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON401() *ErrorModel {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON403 returns the response for an HTTP 403 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON403() *ErrorModel {
	return r.ApplicationproblemJSON403
}

// GetApplicationproblemJSON413 returns the response for an HTTP 413 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON413() *ErrorModel {
	return r.ApplicationproblemJSON413
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON422() *ErrorModel {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON429 returns the response for an HTTP 429 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON429() *ErrorModel {
	return r.ApplicationproblemJSON429
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON503() *ErrorModel {
	return r.ApplicationproblemJSON503
}

// GetApplicationproblemJSON504 returns the response for an HTTP 504 `application/problem+json` response
func (r CreateCostReportResponse) GetApplicationproblemJSON504() *ErrorModel {
	return r.ApplicationproblemJSON504
}

// GetBody returns the raw response body bytes
func (r CreateCostReportResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateCostReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCostReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateCostReportResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateCostForecastWithBodyWithResponse Calculate a cost forecast
//
// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
func (c *ClientWithResponses) CreateCostForecastWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCostForecastResponse, error) {
	rsp, err := c.CreateCostForecastWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCostForecastResponse(rsp)
}

// CreateCostForecastWithResponse Calculate a cost forecast
//
// Projects the trailing daily average over a future period, up to 90 days. The result is an estimate.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/cost_forecasts (the `CreateCostForecast` operationId).
func (c *ClientWithResponses) CreateCostForecastWithResponse(ctx context.Context, body CreateCostForecastJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCostForecastResponse, error) {
	rsp, err := c.CreateCostForecast(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCostForecastResponse(rsp)
}

// CreateCostReportWithBodyWithResponse Calculate a cost and usage report
//
// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
func (c *ClientWithResponses) CreateCostReportWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCostReportResponse, error) {
	rsp, err := c.CreateCostReportWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCostReportResponse(rsp)
}

// CreateCostReportWithResponse Calculate a cost and usage report
//
// Returns an ephemeral report for an inclusive start and exclusive end. Project tokens are restricted to their own project; authorized administrators may query all projects.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/cost_reports (the `CreateCostReport` operationId).
func (c *ClientWithResponses) CreateCostReportWithResponse(ctx context.Context, body CreateCostReportJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCostReportResponse, error) {
	rsp, err := c.CreateCostReport(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCostReportResponse(rsp)
}

// ParseCreateCostForecastResponse parses an HTTP response from a CreateCostForecastWithResponse call
func ParseCreateCostForecastResponse(rsp *http.Response) (*CreateCostForecastResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCostForecastResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ForecastResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON504 = &dest

	}

	return response, nil
}

// ParseCreateCostReportResponse parses an HTTP response from a CreateCostReportWithResponse call
func ParseCreateCostReportResponse(rsp *http.Response) (*CreateCostReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCostReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 504:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON504 = &dest

	}

	return response, nil
}
