// Code generated by go run ./internal/genenums. DO NOT EDIT.

package costexplorer

// FilterServicesValues returns every FilterServices the schema accepts. Each call returns a new slice.
func FilterServicesValues() []FilterServices {
	return []FilterServices{Compute, Image, Volume}
}

// ForecastRequestGranularityValues returns every ForecastRequestGranularity the schema accepts. Each call returns a new slice.
func ForecastRequestGranularityValues() []ForecastRequestGranularity {
	return []ForecastRequestGranularity{ForecastRequestGranularityDaily, ForecastRequestGranularityMonthly}
}

// ForecastRequestMetricValues returns every ForecastRequestMetric the schema accepts. Each call returns a new slice.
func ForecastRequestMetricValues() []ForecastRequestMetric {
	return []ForecastRequestMetric{ForecastRequestMetricCost}
}

// RequestGranularityValues returns every RequestGranularity the schema accepts. Each call returns a new slice.
func RequestGranularityValues() []RequestGranularity {
	return []RequestGranularity{RequestGranularityDaily, RequestGranularityHourly, RequestGranularityMonthly}
}

// RequestGroupByValues returns every RequestGroupBy the schema accepts. Each call returns a new slice.
func RequestGroupByValues() []RequestGroupBy {
	return []RequestGroupBy{ProjectId, Region, ResourceId, Service, UsageType}
}

// RequestMetricsValues returns every RequestMetrics the schema accepts. Each call returns a new slice.
func RequestMetricsValues() []RequestMetrics {
	return []RequestMetrics{RequestMetricsCost, RequestMetricsUsageQuantity}
}
