# Regenerates the client from the schema a cost-explorer deployment serves:
#   make generate SPEC_URL=https://cost-explorer.example.com/openapi-3.0.yaml
# SPEC_URL may also be a local file.
OAPI_CODEGEN := go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0

.PHONY: generate
generate:
	@test -n "$(SPEC_URL)" || { echo "set SPEC_URL to a deployment's /openapi-3.0.yaml, or a local file"; exit 1; }
	@spec=$$(mktemp) && trap 'rm -f "$$spec"' EXIT && \
	case "$(SPEC_URL)" in http://*|https://*) curl -fsSL "$(SPEC_URL)" -o "$$spec" ;; *) cp "$(SPEC_URL)" "$$spec" ;; esac && \
	$(OAPI_CODEGEN) -config oapi-codegen.yaml "$$spec" && \
	version=$$(awk '/^info:/{f=1; next} f && /^  version:/{print $$2; exit} f && /^[^ ]/{exit}' "$$spec") && \
	printf '// Code generated by make generate. DO NOT EDIT.\n\npackage costexplorer\n\n// SpecVersion is the cost-explorer build whose served schema this client was generated from.\nconst SpecVersion = "%s"\n' "$$version" > spec_version.gen.go && \
	echo "generated from cost-explorer $$version"
