// Copyright 2026 VEXXHOST, Inc.
// SPDX-License-Identifier: Apache-2.0

// Command genenums writes enums.gen.go: for every enum oapi-codegen generated (a type
// with a Valid method), a function returning all its values. Consumers then accept
// exactly what the served schema accepts, and pick up a new value when the client is
// regenerated, instead of keeping their own copy of the list.
//
// It reads costexplorer.gen.go rather than the schema, so it needs no YAML parser and
// lists exactly the constants Valid accepts. Run it from the module root.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
)

const (
	input  = "costexplorer.gen.go"
	output = "enums.gen.go"
)

func main() {
	file, err := parser.ParseFile(token.NewFileSet(), input, nil, 0)
	if err != nil {
		log.Fatal(err)
	}
	// cases are the constants each Valid method accepts, which the list must match.
	cases := map[string][]string{}
	values := map[string][]string{}
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Name.Name == "Valid" && d.Recv != nil && len(d.Recv.List) == 1 {
				if id, ok := d.Recv.List[0].Type.(*ast.Ident); ok {
					cases[id.Name] = validCases(d)
				}
			}
		case *ast.GenDecl:
			if d.Tok != token.CONST {
				continue
			}
			for _, spec := range d.Specs {
				v := spec.(*ast.ValueSpec)
				if id, ok := v.Type.(*ast.Ident); ok {
					for _, name := range v.Names {
						values[id.Name] = append(values[id.Name], name.Name)
					}
				}
			}
		}
	}
	names := make([]string, 0, len(cases))
	for name, accepted := range cases {
		if len(values[name]) == 0 {
			log.Fatalf("%s has a Valid method but no constants", name)
		}
		if !sameSet(accepted, values[name]) {
			log.Fatalf("%s: Valid accepts %v but the constants are %v", name, accepted, values[name])
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./internal/genenums. DO NOT EDIT.\n\npackage costexplorer\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\n// %sValues returns every %s the schema accepts. Each call returns a new slice.\nfunc %sValues() []%s {\n\treturn []%s{", name, name, name, name, name)
		for i, v := range values[name] {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(v)
		}
		b.WriteString("}\n}\n")
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(output, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// validCases returns the identifiers in the case clauses of a Valid method's switch.
func validCases(fn *ast.FuncDecl) []string {
	var names []string
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		if clause, ok := n.(*ast.CaseClause); ok {
			for _, expr := range clause.List {
				if id, ok := expr.(*ast.Ident); ok {
					names = append(names, id.Name)
				}
			}
		}
		return true
	})
	return names
}

func sameSet(a, b []string) bool {
	a, b = append([]string(nil), a...), append([]string(nil), b...)
	sort.Strings(a)
	sort.Strings(b)
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
